menu:
    Blog: /
    Archive: /archives/
    Weibo: https://weibo.com/u/2698628733
    GitHub: https://github.com/RecherJ
    RSS: atom.xml

favicon: /favicon.ico
logo: /favicon.png
userIcon: /images/if_weather.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
# ga: UA-xxxxxxxx-x

# Copyright Infomation
startyear: 2016
